gdesmott/system-deps

- src/lib.rs
- src/test.rs
- src/tests/toml-override-name/Cargo.toml
When the default feature overrides the name, also use it in the other features unless another override is declared there.
> Inherit the default name override in features

- Cargo.toml
- src/lib.rs
- src/test.rs
- src/tests/testanotherlib.pc
- src/tests/testlib.pc
- src/tests/toml-two-libs/Cargo.toml
> add helpers aggregating settings from all libraries

- Cargo.toml
- src/lib.rs
- src/metadata.rs
- src/test.rs
- src/tests/toml-invalid-cfg/Cargo.toml
- src/tests/toml-os-specific/Cargo.toml
> allow to define target specific dependencies

- src/metadata.rs
> tests: don't use relative paths to find Cargo.toml

- Cargo.toml
- src/lib.rs
- src/metadata.rs
- src/test.rs
With this, no more proc-macro (which was the biggest problem). It makes the code more explicit and much faster to compile and reducing the network usage when getting the crates for the first time.
I splitted the removal in different commits to make it easier to review.
Fixes #49.
> Remove dependencies

- src/lib.rs
- src/test.rs
- src/tests/teststaticlib.pc
- src/tests/toml-static/Cargo.toml
I had an issue compiling https://github.com/rust-av/dav1d-rs with `SYSTEM_DEPS_DAV1D_LINK=static`
`libdav1d` has the implicit dynamically linked dependency `dl` on linux, which caused issues, as every dependency of the library (which is `dl` and `dav1d`) is linked statically if specified with `SYSTEM_DEPS_<NAME>_LINK`
This PR is mostly copied code from the `pkg_config` crate (specifically the private function `is_static_available`). It checks for each dependency of a library, if the dependency is available as static library and if not, it tries to link dynamically.
I'm not sure if there is a more elegant solution for this issue.
> Fix statically linked libraries that have dynamically linked dependencies

- src/lib.rs
- src/test.rs
Otherwise they come out in non-reproducible order, and that order leaks into
target binaries.
Signed-off-by: Alexander Kanavin <alex@linutronix.de>
> Sort dependencies before using them

- Cargo.toml
- src/lib.rs
The heck crate has been updated, and other crates are using the latest versions already. However, 0.4 has some breaking changes compared to 0.3, which I took care of in this PR. The heck repository contains a [changelog](https://github.com/withoutboats/heck/blob/dbcfc7b8db8e532d1fad44518cf73e88d5212161/CHANGELOG.md) with more information.
> Update heck to 0.4

- Cargo.toml
IIUC this will allow using recently added Rust's new target.
Curently released version fails with: https://gist.github.com/lazka/d7f8fa3d605bdd31ed7bf16a2ff8801c but unfortunately I don't have AArch64 machine to test it.
> Update `cfg-expr` to version 0.11

- Cargo.toml
- src/lib.rs
- src/test.rs
Apparently [alpine patches rustc](https://github.com/alpinelinux/aports/blob/master/community/rust/alpine-target.patch) and adds targets that aren't in the official compiler, so this PR just adds support for falling back to attempting to parse the triple to do evaluation, rather than failing for those with patched compilers.
Resolves: https://github.com/EmbarkStudios/cfg-expr/issues/55
> Add support for non-builtin targets

- src/lib.rs
- src/metadata.rs
- src/test.rs
- src/tests/testlib-2.0.pc
- src/tests/testlib-3.0.pc
- src/tests/toml-fallback-names/Cargo.toml
- src/tests/toml-version-fallback-names/Cargo.toml
This PR adds support for `fallback-names` to allow dealing with different names on different platforms. It also updates the documentation and adds tests. The user can specify `fallback-names` directly on the dependency entry, and on the version overrides.
> Add fallback names to probe to account for platform differences

- src/lib.rs
- src/test.rs
This allows a user to statically link a library even when not using pkg-config as source. Previously, if SYSTEM_DEPS_<LIB>_NO_PKG_CONFIG was set, the SYSTEM_DEPS_<LIB>_LINK=static configuration was ignored.
Since the user already went above and beyond to issue a strong intent of static linking, no check is performed whether the file actually exists. The linker will scream if something is wrong.
> Honor manual requests for static linking

- Cargo.toml
The library fails to compile with versions older than 0.3.10, and your test suite fails to compile with versions older than 0.3.23
> Bump pkg-config to 0.3.23

- Cargo.toml
to fix minimal-versions build
cf https://github.com/EmbarkStudios/cfg-expr/pull/63
> bump minimum required cfg-expr

- src/lib.rs
- src/metadata.rs
- src/test.rs
- src/tests/toml-version-range-unsatisfied/Cargo.toml
- src/tests/toml-version-range/Cargo.toml
This now supports expressions in the form
* "1.2" or ">= 1.2" for at least version 1.2
* ">= 1.2, < 2.0" for at least version 1.2 and less than version 2.0
Fixes https://github.com/gdesmott/system-deps/issues/60
----
@gdesmott Does this look reasonable to you? As discussed, semver can't really be used here because pkg-config versions don't follow semver. A version of "1.2" is semver ">= 1.2, < 2.0" and that is more semantics than pkg-config versions have.
> Implement support for requiring dependency version ranges

- src/lib.rs
This is needed towards building GStreamer's Rust plugins statically on Windows.
CC @nirbheek
> Don't ignore transitive imports when probing a static library

- src/lib.rs
- src/test.rs
- src/tests/testlibwithrpath.pc
- src/tests/toml-rpath/Cargo.toml
Hi all,
This MR implements support for forwarding `LDFLAGS` from pkg-config modules. These are already detected in the `pkg-config` crate, but were not made available to `system-deps` consumers. In particular `-Wl,-rpath,/a/b/c` flags are essential to loading relocated libraries in Apple platforms.
For related issues, see:
- https://github.com/rust-lang/cargo/issues/9554
- https://github.com/rust-lang/cargo/issues/7846
cc @sdroege
> Add support for linker flags

- Cargo.toml
That's the version which introduced Library.ld_args that we are now using.
Fix #94
> bump minimal pkg-config version to 0.3.25

- README.md
- src/lib.rs
- Fix `Library::linker_args` warning when building docs.
- Fix TOML fenced code not surrounded by fences.
- Polite a bit spaces between lists and headers.
> Fix some errors in docs

- Cargo.toml
As the title says.
https://github.com/EmbarkStudios/cfg-expr/releases/tag/0.17.0
> Update cfg-expr to 0.17

- src/tests/toml-fallback-names/Cargo.toml
- src/tests/toml-feature-not-string/Cargo.toml
- src/tests/toml-feature-versions/Cargo.toml
- src/tests/toml-good/Cargo.toml
- src/tests/toml-invalid-cfg/Cargo.toml
- src/tests/toml-missing-key/Cargo.toml
- src/tests/toml-not-table/Cargo.toml
- src/tests/toml-optional/Cargo.toml
- src/tests/toml-os-specific/Cargo.toml
- src/tests/toml-override-name/Cargo.toml
- src/tests/toml-rpath/Cargo.toml
- src/tests/toml-static/Cargo.toml
- src/tests/toml-two-libs/Cargo.toml
- src/tests/toml-unexpected-key/Cargo.toml
- src/tests/toml-version-fallback-names/Cargo.toml
- src/tests/toml-version-in-table-not-string/Cargo.toml
- src/tests/toml-version-missing/Cargo.toml
- src/tests/toml-version-names/Cargo.toml
- src/tests/toml-version-not-string/Cargo.toml
- src/tests/toml-version-range-unsatisfied/Cargo.toml
- src/tests/toml-version-range/Cargo.toml
When using `system-deps` as a git or local dependency instead of the version from `crates.io`, cargo generates errors because the `Cargo.toml` files from the tests don't have the [`name`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-name-field) field, even if they are not real manifests. It still compiles, but the output is very verbose and it could be misleading.
```
error: missing field `name`
--> ../../../.cargo/git/checkouts/system-deps-3c68ab912ff25118/6fcbb37/src/tests/toml-fallback-names/Cargo.toml:1:2
|
1 | [package.metadata.system-deps.test_lib]
|  ^^^^^^^
|
... (many lines like this)
```
This PR just adds the field to the existing manifest with the same name as the test. This shouldn't have any other effects than removing the warnings.
Tested with `cargo 1.82.0 …
> Add names to test manifests
